"""rename department

Revision ID: 477e5aac0f19
Revises: 3992ec7d7584
Create Date: 2024-04-06 11:16:47.703810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477e5aac0f19'
down_revision = '3992ec7d7584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
